on:
  push:
    paths: 
      - "algorithm/*"
  pull_request:
    paths: 
      - "algorithm/*"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
    
      - name: Install mip_matching
        run: |
          cd algorithm
          python -m pip install -e .

      - name: Run tests
        run: |
          cd algorithm
          python -m unittest discover -p "*test.py"
          
